recipes:
  super_paper_crafting: # output
    material: 'PAPER'
    name: '&6Super&cPaper'
    lore:
      - ''
      - 'This is a Super Paper'
    recipe: # recipe
      - " B "  # Empty space = empty slot
      - "BBB"
      - " B "

  another_recipe_crafting:
    material: 'DIAMOND'
    name: '&bAnother Recipe'
    lore:
      - '&aCraft this with diamonds!'
    recipe:
      - "BBB"
      - "B B"
      - "BBB"

items-for-recipe:
  book:
    char: 'B'
    material: BOOK
